### PR TITLE
Remove abandoned info in init search

### PR DESCRIPTION
**Pull request by herndlm**
This seems to be dead code because `abandoned` is never set, not even for e.g. `fzaninotto/faker`

Fixes a phpstan error, but wanted to move this to a dedicated PR, because I might be completely wrong here..

### CODE REVIEW

**Comment by herndlm** [comment]
In case this is correct - I have the feeling this should then be a dedicated PR to composer/composer instead of hiding in the phpstan update

**Comment by Seldaek** [comment]
Hmm interesting, looks like I actually broke this when bumping to PHPStan level 3 ;) 

https://github.com/composer/composer/commit/4940009f8377d06b9fb48df0cbe67193e0989830#diff-fcfc43da4ed67efe626640158c4aa49d5a162efd01e8844f0fbbc655fcffbddeL431-R433

Because the API does return abandoned state https://packagist.org/search.json?q=faker so the InitCommand code did work..

Not sure how to best deal with this, I guess it'd have to have optional fields for abandoned on the RepositoryInterface's search return value?

**Comment by herndlm** [comment]
> Hmm interesting, looks like I actually broke this when bumping to PHPStan level 3 ;)
> 
> [composer@4940009#diff-fcfc43da4ed67efe626640158c4aa49d5a162efd01e8844f0fbbc655fcffbddeL431-R433](https://github.com/composer/composer/commit/4940009f8377d06b9fb48df0cbe67193e0989830#diff-fcfc43da4ed67efe626640158c4aa49d5a162efd01e8844f0fbbc655fcffbddeL431-R433)
> 
> Because the API does return abandoned state https://packagist.org/search.json?q=faker so the InitCommand code did work..
> 
> Not sure how to best deal with this, I guess it'd have to have optional fields for abandoned on the RepositoryInterface's search return value?

Ah I see, thx for digging this up. Without knowing too much about other involved implementations or implications of that change I'd say that it makes sense to add it as optional field.

I'd simply create a bugfix PR for that later today if that's fine

**Comment by Seldaek** [comment]
Yes bugfix pr sounds good, definitely unrelated to the phpstan fixes

**Pull request closed without merging**
